### ISSUE TITLE
Location column in Group Finder View does not show zonenames, only distance

### ISSUE THREAD

**Issue by NorfolkXX** [GuimDev/ProvisionsTeamFormation#12]
Hi, since around mid of June 2018, the addon in version 1.2.6b - latest on esoui - doesnt show zonenames in group finder view. Sometimes when opening the view, zonenames blink up for a short moment like they should be visible but within 0.5 seconds then the column is blanked out. 

It does show distances for player in same zones/dungeons, though - but no zonenames if a group member is in a different zone. Then the field is empty/black.

**Comment by GuimDev** [comment]
It's bug of ESO.

    SI_SOCIAL_LIST_ALLIANCE_FORMAT == nil

I fix it, to write the string value "<<C:1>>".

I replace : 

    text = zo_strformat(SI_SOCIAL_LIST_ALLIANCE_FORMAT, zone)

to : 

    text = zo_strformat("<<C:1>>", zone)

**Comment by GuimDev** [comment]
Thanks @NorfolkXX
